Vagrant.configure("2") do |config|
 if Vagrant.has_plugin? "vagrant-vbguest"
 config.vbguest.no_install = true
 config.vbguest.auto_update = false
 config.vbguest.no_remote = true
 end
 config.vm.define :servidoruno do |servidoruno|
 servidoruno.vm.box = "centos/stream8"
 servidoruno.vm.network :private_network, ip: "192.168.50.2"
 servidoruno.vm.hostname = "servidoruno"
 end
 config.vm.define :servidordos do |servidordos|
 servidordos.vm.box = "centos/stream8"
 servidordos.vm.network :private_network, ip: "192.168.50.3"
 servidordos.vm.hostname = "servidordos"
 end
 config.vm.define :clienteparcial do |clienteparcial|
 clienteparcial.vm.box = "centos/stream8"
 clienteparcial.vm.network :private_network, ip: "192.168.50.4"
 clienteparcial.vm.hostname = "clienteparcial"
 end
end